### ISSUE TITLE
set up code on slac gpus?

### ISSUE THREAD

**Issue by cpadavis** [cpadavis/billy#14]

**Comment by drphilmarshall** [comment]
I think you mean, "SET UP CODE ON SLAC GPUs!!!1!"

**Comment by cpadavis** [comment]
status: I got caffe working on my laptop. I think I have most of the libraries for the slac ki-gpu, but a too-old version of opencv was installed and so the code failed to compile there

**Comment by drphilmarshall** [comment]
Sweet! Glenn's your man for installation support at SLAC, if you can't over
ride the opencvs package. Man this is going to rock.

**Comment by cpadavis** [comment]
I've been consulting with Stuart about this :)

**Comment by cpadavis** [comment]
sherlock works great for this. closing
