### ISSUE TITLE
name

### ISSUE THREAD

**Issue by drphilmarshall** [cpadavis/billy#17]
Previously I suggested "SpotterBot" for this machine classifier, because "Bot" has some resonance in the Zooniverse world. 

Any fun name would do though - I am imagining making a Zooniverse account in this code's name, and posting images and comments from it (by hand at first, and then possibly later by automagic). So the name of this code should look good in Zooniverse forum.

I note that the letters "CNN" are contained in the word "cunning" - suggesting the possible name "TheFox." Or, more self-deprecatingly, "Baldrick" (a BBC comedy reference).

**Comment by drphilmarshall** [comment]
Development on this issue seems to be non-existent, for some reason.

**Comment by cpadavis** [comment]
BILLY
