### ISSUE TITLE
test caffe convnet code

### ISSUE THREAD

**Issue by cpadavis** [cpadavis/billy#22]
since I have caffe installed on my laptop, AND I have the catalog, I should check that this all works on my laptop. When I close this issue, I should also report approximately how long this took to ran on my laptop, and how badly it killed my ability to use it for other things (internet, ssh)

**Comment by drphilmarshall** [comment]
Make sure you have Activity Monitor running and visible - I wonder if you
'll see the CPU usage looking normal, but the screen refresh rate slowed by
the GPU usage?

**Comment by cpadavis** [comment]
caffe works but it looks like we'll mostly be sticking with theano (which works on laptop, sherlock, and stanford gpu clusters)
