### ISSUE TITLE
Training Galaxy Zoo

### ISSUE THREAD

**Issue by cpadavis** [cpadavis/billy#25]
SpaceWarps training labels are integers of shape (N_training,), but Galaxy Zoo training labels are floats (N_training, 37), so we need to be able to train on that as well.

**Comment by ajmcleod** [comment]
This works now. You need to specify 'cost_function': 'rms_error' or  'cost_function': 'log_likelihood' in the softmax layer of network_architecture. The former should be used for the galaxy zoo data, the latter for space warps data. Examples in random_galzoo_hyperparameter_instance_ajm.py and random_sw_hyperparameter_instance_ajm.py

**Comment by drphilmarshall** [comment]
Excellent! This seems key.
