### ISSUE TITLE
make sure overlap_max_pool and alexnet architecture works

### ISSUE THREAD

**Issue by cpadavis** [cpadavis/billy#34]

**Comment by ajmcleod** [comment]
Assuming overlap_max_pool() works, is there a reason not to rename it max_pool() and give it a default stride?

**Comment by cpadavis** [comment]
Wasn't sure how you felt about that versus requiring that both always be
specified.

**Comment by ajmcleod** [comment]
Let's just combine them. But first I have to get pandas working on sherlock...

**Comment by cpadavis** [comment]
done
